# DS4400 - Homework 1
## Computational Problems

**Author:** Vignan Kamarthi  

In [1]:
import numpy as np
import pandas as pd

---
## Problem 4 Part 2: Matrix Inverse

Generate 3 random 3×3 matrices with integers from -10 to 10, compute their inverses, and verify A·A⁻¹ = I.

In [2]:
np.random.seed(8)

matrices = [np.random.randint(-10, 11, size=(3, 3)) for i in range(3)]

for i, A in enumerate(matrices):
    print(f"Matrix {i+1}:")
    print(A)
    print("\n")

    det = np.linalg.det(A)
    print(f"Determinant of Matrix {i+1}: {det}")
    print("\n")

    if det == 0:
        print("Matrix is not invertible")
    else:
        inv = np.linalg.inv(A)
        print(f"Inverse of Matrix {i+1}:\n{inv}")
        print("\n")
        print("Verification (A * A^(-1) = I): ")
        print("\n")
        product_I = np.dot(A, inv)
        print(np.round(product_I, 10))
        print("\n")
        print("--------------------------------------------------")



Matrix 1:
[[-7 10  7]
 [-1 -5 -2]
 [ 9 -2  6]]


Determinant of Matrix 1: 446.9999999999998


Inverse of Matrix 1:
[[-0.07606264 -0.1655481   0.03355705]
 [-0.02684564 -0.23489933 -0.04697987]
 [ 0.10514541  0.17002237  0.10067114]]


Verification (A * A^(-1) = I): 


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


--------------------------------------------------
Matrix 2:
[[ 3  7  9]
 [ 0  2  3]
 [-1  5 -8]]


Determinant of Matrix 2: -95.99999999999999


Inverse of Matrix 2:
[[ 0.32291667 -1.05208333 -0.03125   ]
 [ 0.03125     0.15625     0.09375   ]
 [-0.02083333  0.22916667 -0.0625    ]]


Verification (A * A^(-1) = I): 


[[ 1. -0. -0.]
 [-0.  1. -0.]
 [ 0.  0.  1.]]


--------------------------------------------------
Matrix 3:
[[ 8  4 -4]
 [-1  9 -6]
 [-3  0 -1]]


Determinant of Matrix 3: -112.00000000000006


Inverse of Matrix 3:
[[ 0.08035714 -0.03571429 -0.10714286]
 [-0.15178571  0.17857143 -0.46428571]
 [-0.24107143  0.10714286 -0.67857143]]


Verification (A * A^(-1) = I): 


[

---
## Problem 5: Average, Variance, and Correlation

Exploratory data analysis on the house price dataset.

In [ ]:
df = pd.read_csv('kc_house_data.csv')

df = df.drop(columns=['id', 'date', 'zipcode'])

# Making sure the data is loaded correctly
print(f"Dataset shape: {df.shape}")
print(f"Columns: {list(df.columns)}")
df.head()

Dataset shape: (21613, 18)
Columns: ['price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'lat', 'long', 'sqft_living15', 'sqft_lot15']


price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0         3       1.00         1180      5650     1.0           0   
1  538000.0         3       2.25         2570      7242     2.0           0   
2  180000.0         2       1.00          770     10000     1.0           0   
3  604000.0         4       3.00         1960      5000     1.0           0   
4  510000.0         3       2.00         1680      8080     1.0           0   

   view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3      7        1180              0      1955             0   
1     0          3      7        2170            400      1951          1991   
2     0          3      6         770              0      1933             0   
3     0          5      7        1050            910      1965             0   
4     0          3      8        1680              0      1987             0   

       lat     long  sqft_living15  sqft_lot15  
0  47.5112 -122.257           1340        5650  
1  47.7210 -122.319           1690        7639  
2  47.7379 -122.233           2720        8062  
3  47.5208 -122.393           1360        5000  
4  47.6168 -122.045           1800        7503

### Part 1: Average, Min, Max, Variance for each feature

In [17]:
statistics = pd.DataFrame({
    'Average': df.mean(),
    # Median because median household statistics are a better measure of central tendency for skewed data and for fun lol
    'Median': df.median(),
    'Mean and Median Difference': np.abs(df.mean() - df.median()),
    'Min': df.min(),
    'Max': df.max(),
    'Variance': df.var()
})

print(statistics.to_string())
print("\n")

lowest_avg_feature = statistics['Average'].idxmin()
highest_avg_feature = statistics['Average'].idxmax()
lowest_var_feature = statistics['Variance'].idxmin()
highest_var_feature = statistics['Variance'].idxmax()

print(f"Feature with Lowest Average: {lowest_avg_feature} ({statistics.loc[lowest_avg_feature, 'Average']:.4f})")
print(f"Feature with Highest Average: {highest_avg_feature} ({statistics.loc[highest_avg_feature, 'Average']:.4f})")
print(f"Feature with Lowest Variance: {lowest_var_feature} ({statistics.loc[lowest_var_feature, 'Variance']:.4f})")
print(f"Feature with Highest Variance: {highest_var_feature} ({statistics.loc[highest_var_feature, 'Variance']:.4f})")

                     Average       Median  Mean and Median Difference         Min           Max      Variance
price          540088.141767  450000.0000                90088.141767  75000.0000  7.700000e+06  1.347824e+11
bedrooms            3.370842       3.0000                    0.370842      0.0000  3.300000e+01  8.650150e-01
bathrooms           2.114757       2.2500                    0.135243      0.0000  8.000000e+00  5.931513e-01
sqft_living      2079.899736    1910.0000                  169.899736    290.0000  1.354000e+04  8.435337e+05
sqft_lot        15106.967566    7618.0000                 7488.967566    520.0000  1.651359e+06  1.715659e+09
floors              1.494309       1.5000                    0.005691      1.0000  3.500000e+00  2.915880e-01
waterfront          0.007542       0.0000                    0.007542      0.0000  1.000000e+00  7.485226e-03
view                0.234303       0.0000                    0.234303      0.0000  4.000000e+00  5.872426e-01
condition 

### Part 2: Correlation Coefficients with Price

In [ ]:
correlations = df.corr()['price'].drop('price')

print("Correlation with price:")
print(correlations.sort_values())
print("\n")

positive_correlations = correlations[correlations > 0]
print(f"Positively correlated features ({len(positive_correlations)}):")
print(list(positive_correlations.index))
print("\n")

print(f"Highest positive correlation: {correlations.idxmax()} ({correlations.max():.4f})")

Correlation with price:
long             0.021626
condition        0.036362
yr_built         0.054012
sqft_lot15       0.082447
sqft_lot         0.089661
yr_renovated     0.126434
floors           0.256794
waterfront       0.266369
lat              0.307003
bedrooms         0.308350
sqft_basement    0.323816
view             0.397293
bathrooms        0.525138
sqft_living15    0.585379
sqft_above       0.605567
grade            0.667434
sqft_living      0.702035
Name: price, dtype: float64


Positively correlated features (17):
['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'lat', 'long', 'sqft_living15', 'sqft_lot15']


Highest positive correlation: sqft_living (0.7020)


### Part 3: Features with Negative Correlation to Price

In [27]:
negative_correlations = correlations[correlations < 0]

if len(negative_correlations) == 0:
    print("No features have negative correlation with price.")
else:
    print("Features with negative correlation to price:")
    print(negative_correlations.sort_values())

No features have negative correlation with price.
